# Generated by Django 5.1.4 on 2025-01-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('social_media', 'Social Media'), ('education', 'Education'), ('tools', 'Tools')], default='general', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='sub_category',
            field=models.CharField(choices=[('games', 'Games'), ('utilities', 'Utilities'), ('productivity', 'Productivity'), ('others', 'Others')], default='Uncategorized', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='app_link',
            field=models.URLField(max_length=255),
        ),
    ]
