# Generated by Django 5.1.4 on 2025-01-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_app_category_app_sub_category_alter_app_app_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='app',
            name='points',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='app',
            name='sub_category',
            field=models.CharField(max_length=100),
        ),
    ]
