# Generated by Django 5.1.4 on 2025-01-13 17:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_app_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='screenshot',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='app',
            name='category',
        ),
        migrations.RemoveField(
            model_name='app',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='app',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='application.app'),
        ),
    ]
