# Generated by Django 5.1.4 on 2025-01-14 04:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_rename_screenshot_screenshot_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.CharField(default='default_category', max_length=100),
        ),
        migrations.AddField(
            model_name='app',
            name='sub_category',
            field=models.CharField(default='default_sub_category', max_length=100),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='app_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='app_icons/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.app'),
        ),
    ]
