# Generated by Django 5.1.4 on 2025-01-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_app_category_app_sub_category_screenshot_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(default='default_icon.png', upload_to='app_icons/'),
        ),
    ]
