# Generated by Django 5.1.4 on 2025-01-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_app_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='app_icons/'),
        ),
    ]
